# from setup import basedir
import datetime

class BaseConfig(object):
    SECRET_KEY = "SO_SECURE"
    DEBUG = True
    NR_APIKEY = "72Tk0aXkXF9-WZ98x_TiysGxGt1-UcmR"
    # SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
    # SQLALCHEMY_TRACK_MODIFICATIONS = True
    BLOCK_USER_CREATION = False
    indexDate = datetime.datetime.today().strftime("%Y-%m-%d")
    TestNewRelicTransactionApps = {"apps":
                        [
                            "AuthNet"
                        ]
    }
    # NewRelicApps = {"apps": ["AuthNet", "DLV API", "Podcast Blog", "Prod Queuing", "VO Content Server",
                            # "VO.DLV Content Server", "WWW Content Server", "YL API0", "YLPC", "YLPC.ShipmentFulfillmentAPIV2", "YLPC.Warehouse"]}
    TestSystemSample = {"apps":
        [
            "VO NSB Distributor",
            "JDE Expense",
            "JDE HTML",
            "JDE PRODDB",
            "STAGE DLV",
            "CLN VO DLV API",
            "Wellness",
            "VO ElasticSearch",
            "Stage VO",
            "LabVantage",
            "JDE Deployment",
            "Infrastructure Tools",
            "JDE BI",
            "DSI",
            "JDE Moover",
            "Deploy and Dev Tools",
            "Clone VO NSB Audit",
            "JDE FTP",
            "JDE Real Time Events",
            "Kount",
            "Stage Content Server",
            "Cymbeo",
            "JDE E1",
            "ProPay",
            "Classic DLV",
            "VO Memcached",
            "Clone VO NSB Distributor",
            "VO Content",
            "SQL",
            "NOT",
            "STAGE API",
            "VO Micro Services",
            "Clone VO Micro Services",
            "Taiwan",
            "VO ACL Worker",
            "VO",
            "VO API",
            "LIMS",
            "ORAPRD DB",
            "Vertex",
            "ORAVOPRD DB",
            "Accounting",
            "BI",
            "JDE",
            "CVENT-API",
            "CLONE VO Micro Services",
            "VO NSB Worker",
            "VO DLV API",
            "Events",
            "VO NSB Audit",
            "CLONE VO ACL Worker,CLONE YL.LegacyPublisher",
            "VO Logstash",
            "Communication",
            "GreatPlains",
            "CLONE VO API",
            "Zerto",
            "NewRelic",
            "Classic",
            "Clone VO DLV API",
            "Oracle Apps",
            "CMS-Global",
            "Clone VO Content",
            "JDE BSSV",
            "Clone VO ACL Worker,Clone JDE.LegacySubscriber",
            "Splunk"
        ]
    }

    TestNewRelicMicroservices = {"services": ["Tax Service"]}
    # NewRelicMicroservices = {"services": ["Tax Service", "Shipping", "Shipping Importer", "Catalog Importer", "Catalog", "Address",
                                          #"Contest Admin", "Contest Executor", "Contest Executor", "Contest", "VO Content Server"]}
    # Prod
    ProdNewRelicMicroservices = {"services":
        [
            "DLV API",
            "Podcast Blog",
            "AuthNet",
            "JoyMain Customer Sync",
            "JoyMain Order Sync",
            "Order Payment",
            "CIA SMTP Sender",
            "Fraud",
            "OrderFulfillmentAPI",
            "Notifications Tasks",
            "Reference Importer",
            "Cybersource Service",
            "YLPC",
            "Stage AuthNet",
            "Customer Programs Processor",
            "Dev Customer Programs",
            "Oily API",
            "Kount",
            "Contest Admin",
            "Payment Service",
            "Shipping",
            "China Agreement Enforcement",
            "Address",
            "VO.DLV Content Server",
            "Contest",
            "Catalog Importer",
            "Classic DLV",
            "Product Recommendation",
            "VO API",
            "Reference Service",
            "Customer Programs",
            "JoyMain Commission Sync",
            "WWW Content Server",
            "YL API",
            "Tax Service",
            "Prod Queuing",
            "YLPC.ShipmentFulfillmentAPI",
            "Catalog",
            "VO Content Server",
            "Shipping Importer",
            "Contest Executor"
        ]
    }
    # Clone
    CloneNewRelicMicroservices = {"services":
        [
            "Clone Contest",
            "Clone Address",
            "Clone JoyMain Commission Sync",
            "Clone Reference Importer",
            "Clone Shipping",
            "Clone API",
            "Clone JoyMain Order Sync",
            "Clone Payment Service",
            "Clone Queuing",
            "Clone Contest Executor",
            "Clone Order Payment",
            "Clone Catalog Importer",
            "Clone Contest Admin",
            "Clone AuthNet",
            "Clone Reference Service",
            "Clone Customer Programs",
            "Clone VO API",
            "Clone Fraud",
            "Clone Catalog",
            "Clone Shipping Importer",
            "Clone Tax Service",
            "Clone DLV API",
            "Clone Cybersource Service",
            "Clone JoyMain Customer Sync",
            "Clone Customer Programs Processor",
            "Clone Product Recommendation"
        ]
    }
    #All
    AllNewRelicMicroservices = {"services":
        [
            "Env5 Shipping",
            "DLV API",
            "Test Podcast Blog",
            "Env6 Catalog",
            "Env10 Payment Service",
            "Dev4 Catalog",
            "Env2 Contest Executor",
            "Env8 Cybersource Service",
            "Dev4 Reference Importer",
            "Env4 Customer Programs Processor",
            "Env7 Address",
            "Test Product Recommendation",
            "Env7 Contest",
            "Env6 Catalog Importer",
            "Clone Contest",
            "Env7 Reference Importer",
            "Podcast Blog",
            "AuthNet",
            "JoyMain Customer Sync",
            "Clone Address",
            "Stage Catalog",
            "Test AuthNet",
            "Stage Payment Service",
            "Clone JoyMain Commission Sync",
            "Env4 Reference Importer",
            "Env4 Contest Admin",
            "Dev4 Product Recommendation",
            "Stage Contest Admin",
            "Dev Contest Admin",
            "Env4 Contest",
            "Stage Cybersource Service",
            "Dev4 JoyMain Commission Sync",
            "Test Customer Programs",
            "Stage Notifications Tasks",
            "Dev Reference Importer",
            "Env10 Customer Programs",
            "Env10 Reference Service",
            "Dev4 Shipping",
            "STAGE API",
            "Dev Customer Programs Processor",
            "JoyMain Order Sync",
            "Order Payment",
            "CIA SMTP Sender",
            "Env9 Contest Admin",
            "Dev Dragon Pay Service",
            "Dev Catalog Importer",
            "Test Payment Service",
            "Env6 Contest Executor",
            "Clone Reference Importer",
            "Env8 Invoicing",
            "Env1 Catalog",
            "Fraud",
            "OrderFulfillmentAPI",
            "Test Reference Service",
            "Notifications Tasks",
            "Env5 Payment Service",
            "Test Contest Admin",
            "Env10 Reference Importer",
            "Env6 Fraud",
            "Env2 Payment Service",
            "Env8 Payment Service",
            "Env8 Contest Admin",
            "Stage Product Recommendation",
            "Env1 Reference Importer",
            "Reference Importer",
            "Dev4 Customer Programs Processor",
            "Env7 Shipping",
            "Cybersource Service",
            "Dev Cybersource Service",
            "Env9 Catalog",
            "Env4 Address",
            "Env1 Customer Programs Processor",
            "Clone Shipping",
            "Env2 Catalog Importer",
            "Env8 AuthNet",
            "YLPC",
            "Stage AuthNet",
            "Env6 Customer Programs Processor",
            "Dev4 Fraud",
            "Env8 Product Recommendation",
            "Env10 Fraud",
            "Env5 Fraud",
            "Env7 Customer Programs Processor",
            "Dev4 Contest Admin",
            "Env5 Catalog Importer",
            "Env4 Catalog",
            "Env9 Customer Programs",
            "Customer Programs Processor",
            "Dev Customer Programs",
            "Env10 Contest",
            "Env3 Shipping Importer",
            "Env10 AuthNet",
            "Env5 Contest Admin",
            "Oily API",
            "Stage VO",
            "Dev Contest",
            "Env2 Shipping Importer",
            "Env9 Reference Importer",
            "Dev Address",
            "Dev Fraud",
            "Clone API",
            "Env5 Contest",
            "Env1 Product Recommendation",
            "Env5 Address",
            "Env5 Reference Importer",
            "Env2 Reference Importer",
            "Test Shipping Importer",
            "Env3 Catalog Importer",
            "Kount",
            "Env8 Contest Executor",
            "Env7 Product Recommendation",
            "Dev Tax Service",
            "Clone JoyMain Order Sync",
            "Env3 Contest Executor",
            "Test Tax Service",
            "Env2 Contest",
            "Env7 Fraud",
            "Dev4 JoyMain Order Sync",
            "Env9 AuthNet",
            "Contest Admin",
            "Env5 Contest Executor",
            "Stage Tax Service",
            "Clone Payment Service",
            "Payment Service",
            "Env6 Customer Programs",
            "Test Shipping",
            "Dev4 Tax Service",
            "Env6 Shipping Importer",
            "Dev4 Payment Service",
            "Env8 Customer Programs Processor",
            "Env8 Contest",
            "Env7 Catalog",
            "Clone Queuing",
            "Clone Contest Executor",
            "Env3 Product Recommendation",
            "Env7 Reference Service",
            "Env3 Contest Admin",
            "Env6 AuthNet",
            "Shipping",
            "Env9 Fraud",
            "Clone Order Payment",
            "Env9 Customer Programs Processor",
            "Env5 Product Recommendation",
            "Env8 Fraud",
            "Dev Reference Service",
            "Env10 Contest Admin",
            "Env10 Tax Service",
            "Env3 AuthNet",
            "Env2 Address",
            "Env10 Cybersource Service",
            "Stage Fraud",
            "Clone Catalog Importer",
            "Env6 Payment Service",
            "Env2 Contest Admin",
            "Env3 Shipping",
            "Env9 Payment Service",
            "Env3 Payment Service",
            "Dev Shipping Importer",
            "China Agreement Enforcement",
            "Address",
            "Env2 Catalog",
            "STAGE DLV",
            "VO.DLV Content Server",
            "Env3 Customer Programs",
            "Stage Reference Service",
            "Dev Catalog",
            "Env9 Shipping Importer",
            "Env4 Reference Service",
            "Env7 AuthNet",
            "Clone Contest Admin",
            "Env8 Shipping Importer",
            "Contest",
            "Clone AuthNet",
            "Test Contest",
            "Env4 Customer Programs",
            "Test Address",
            "Env1 Contest Admin",
            "Catalog Importer",
            "Env3 Address",
            "Env7 Payment Service",
            "Env8 Catalog Importer",
            "Env9 Tax Service",
            "Env5 Customer Programs Processor",
            "Classic DLV",
            "Env4 AuthNet",
            "Env7 Tax Service",
            "Clone Reference Service",
            "Env4 Payment Service",
            "Stage Customer Programs",
            "Env3 Reference Service",
            "Env3 Fraud",
            "Env8 Tax Service",
            "Product Recommendation",
            "Env6 Shipping",
            "Env2 Customer Programs",
            "Stage Contest Executor",
            "VO API",
            "Env2 Reference Service",
            "Env8 Invoice Generator",
            "Stage Reference Importer",
            "Reference Service",
            "Customer Programs",
            "Env3 JoyMain Customer Sync",
            "Env5 Catalog",
            "Clone Customer Programs",
            "Stage Shipping Importer",
            "Env3 Tax Service",
            "Env8 Address",
            "Env9 Catalog Importer",
            "Env1 Reference Service",
            "Env1 Payment Service",
            "Env5 Tax Service",
            "Env5 Shipping Importer",
            "Env10 Customer Programs Processor",
            "Env1 Tax Service",
            "Env2 Tax Service",
            "Env6 Tax Service",
            "Clone VO API",
            "Env6 Contest",
            "Env7 Customer Programs",
            "JoyMain Commission Sync",
            "Env9 Product Recommendation",
            "Env4 Shipping",
            "Test Order Payment",
            "Env6 Reference Importer",
            "Env8 Reference Importer",
            "Env4 Tax Service",
            "Env3 Reference Importer",
            "Env6 Reference Service",
            "Env3 Contest",
            "Test Market Blogs",
            "Env7 Shipping Importer",
            "WWW Content Server",
            "Clone Fraud",
            "Test Catalog Importer",
            "Stage Customer Programs Processor",
            "Clone Catalog",
            "Test Fraud",
            "Dev4 Invoicing",
            "Clone Shipping Importer",
            "Env6 Contest Admin",
            "Env9 Shipping",
            "YL API",
            "Dev4 Reference Service",
            "Env7 Contest Admin",
            "Clone Tax Service",
            "Env1 AuthNet",
            "Env5 Customer Programs",
            "Clone DLV API",
            "Dev Shipping",
            "Env1 Contest Executor",
            "Env2 Shipping",
            "Test Customer Programs Processor",
            "Env10 Catalog Importer",
            "Env4 Fraud",
            "Env8 Shipping",
            "Clone Cybersource Service",
            "Test Catalog",
            "Env10 Address",
            "Test Reference Importer",
            "Dev4 AuthNet",
            "Env1 Fraud",
            "Env8 Catalog",
            "Dev AuthNet",
            "Tax Service",
            "Test Cybersource Service",
            "Env5 AuthNet",
            "Prod Queuing",
            "YLPC.ShipmentFulfillmentAPI",
            "Dev4 Catalog Importer",
            "Dev4 Shipping Importer",
            "Env9 Reference Service",
            "Env4 Shipping Importer",
            "Env2 AuthNet",
            "Env1 Shipping",
            "Catalog",
            "Env10 Product Recommendation",
            "Dev4 Commission",
            "Env8 Customer Programs",
            "Stage Address",
            "Env9 Contest",
            "Dev4 Address",
            "Env8 Reference Service",
            "Env1 Address",
            "Env2 Customer Programs Processor",
            "VO Content Server",
            "Clone JoyMain Customer Sync",
            "Clone Customer Programs Processor",
            "Clone Product Recommendation",
            "Env2 Product Recommendation",
            "Env1 Notifications Tasks",
            "Env6 Product Recommendation",
            "Dev Payment Service",
            "Env10 Shipping Importer",
            "Env3 Customer Programs Processor",
            "Env2 Fraud",
            "Test Video Blog",
            "Env1 Customer Programs",
            "Env7 Contest Executor",
            "Stage Catalog Importer",
            "Env6 Address",
            "Env1 Catalog Importer",
            "Shipping Importer",
            "Contest Executor",
            "Env1 Shipping Importer",
            "Env10 Shipping",
            "Stage Shipping",
            "Dev4 Customer Programs",
            "Env4 Catalog Importer",
            "Stage Contest",
            "Dev4 Contest",
            "Env9 Address",
            "Env10 Excelia",
            "Env10 Catalog",
            "Env4 Contest Executor",
            "Env7 Catalog Importer",
            "Env5 Reference Service",
            "Env1 Contest",
            "Test Dragon Pay Service",
            "Dev Product Recommendation",
            "Env4 Product Recommendation",
            "Env3 Catalog"
        ]
    }

    keysToIgnore = {"host.displayName"}
    es_host = 'localhost'
    #es_host = 'LEI-IT-LT-51693.yleo.us'
    elasticSearchIndex = 'jdtest'
    elasticSearchMapping = {
        # "mappings": {
        #     "_default_": {
        #         "_all": {
        #             "enabled": True,
        #             "norms": False
        #         }, "properties": {
        #             "@timestamp": {
        #                 "type": "date",
        #                 "include_in_all": True
        #             }, "@version": {
        #                 "type": "keyword",
        #                 "include_in_all": True
        #             }
        #         }
        #     }
        # }
    }
    prodAppsQuery = "SELECT uniques(appName) FROM Transaction SINCE '2019-01-03 10:00' until '2019-01-03 10:10' WHERE appName NOT LIKE 'Clone%' AND appName NOT LIKE 'Stage%' AND appName NOT LIKE 'Dev%' AND appName NOT LIKE 'Test%' AND appName NOT LIKE 'Env%'"

class TestingConfig(object):
    """Development configuration."""
    TESTING = True
    DEBUG = True
    WTF_CSRF_ENABLED = False
    # S SQLALCHEMY_DATABASE_URI = 'sqlite:///:memory:'
    DEBUG_TB_ENABLED = True
    PRESERVE_CONTEXT_ON_EXCEPTION = False
